// Copyright (c) 2021 OFFIS e.V.. All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//    
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//    
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software without
//    specific prior written permission.
//    
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// <auto-generated />
using LotsenApp.Client.TanList;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LotsenApp.Client.TanList.Migrations
{
    [DbContext(typeof(TanListContext))]
    [Migration("20200903123343_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("LotsenApp.Client.TanList.TanListModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tan1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tan10")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan10Used")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tan1Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan2")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan2Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan3")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan3Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan4")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan4Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan5")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan5Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan6")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan6Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan7")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan7Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan8")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan8Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tan9")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tan9Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("tan_lists");
                });
#pragma warning restore 612, 618
        }
    }
}
