// <auto-generated />
using LotsenApp.Client.Configuration.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LotsenApp.Client.Configuration.Database.Migrations
{
    [DbContext(typeof(DatabaseConfigurationContext))]
    [Migration("20210826103601_EncryptedConfiguration")]
    partial class EncryptedConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("LotsenApp.Client.Configuration.Database.GlobalConfigurationEntry", b =>
                {
                    b.Property<string>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigurationId");

                    b.ToTable("global_configuration_encrypted");
                });

            modelBuilder.Entity("LotsenApp.Client.Configuration.Database.UserConfigurationEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("user_configuration_encrypted");
                });
#pragma warning restore 612, 618
        }
    }
}
